"""add tmdb fields

Revision ID: 246a87d6d231
Revises: None
Create Date: 2026-05-20 03:30:28.783165

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "246a87d6d231"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("records", sa.Column("tmdb_id", sa.Integer(), nullable=True))
    op.add_column("records", sa.Column("poster_url", sa.Text(), nullable=True))
    op.add_column("records", sa.Column("overview", sa.Text(), nullable=True))
    op.add_column(
        "records", sa.Column("tmdb_rating", sa.Numeric(precision=3, scale=1), nullable=True)
    )
    op.add_column("records", sa.Column("genres", sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("records", "genres")
    op.drop_column("records", "tmdb_rating")
    op.drop_column("records", "overview")
    op.drop_column("records", "poster_url")
    op.drop_column("records", "tmdb_id")
    # ### end Alembic commands ###
