"""add activities table

Revision ID: 7675a43fcd91
Revises: 7b35a5d1ed4d
Create Date: 2026-06-14 11:20:35.436625

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7675a43fcd91"
down_revision: str | Sequence[str] | None = "7b35a5d1ed4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("activity_type", sa.String(length=50), nullable=False),
        sa.Column("object_id", sa.UUID(), nullable=True),
        sa.Column("object_type", sa.String(length=50), nullable=True),
        sa.Column("visibility", sa.String(length=20), server_default="public", nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["user_profiles.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_activities_actor_created", "activities", ["actor_id", sa.text("created_at DESC")]
    )
    op.create_index("idx_activities_object", "activities", ["object_id", "object_type"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_activities_actor_created", table_name="activities")
    op.drop_index("idx_activities_object", table_name="activities")
    op.drop_table("activities")
    # ### end Alembic commands ###
