"""add release_year to records

Revision ID: 8bfcae5f1e34
Revises: 246a87d6d231
Create Date: 2026-05-21 16:38:07.301718

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8bfcae5f1e34"
down_revision: str | Sequence[str] | None = "246a87d6d231"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("records")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "records",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("media_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("season", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("episode", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("rating", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("tmdb_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("poster_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("overview", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "tmdb_rating", sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True
        ),
        sa.Column("genres", postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("records_pkey")),
    )
    # ### end Alembic commands ###
